In [2]:
!git clone https://github.com/ultralytics/yolov5  # clone
%cd yolov5
%pip install -qr requirements.txt comet_ml  # install

import torch
import utils
display = utils.notebook_init()  # checks

YOLOv5 🚀 v7.0-284-g95ebf68f Python-3.12.1 torch-2.3.0 CPU


Setup complete ✅ (8 CPUs, 8.0 GB RAM, 189.1/228.3 GB disk)


tensor([1.], device='mps:0')


In [5]:
%cd /Users/jashtandel/SEM6/UAS/COMP_AGRI/yolov5

/Users/jashtandel/SEM6/UAS/COMP_AGRI/yolov5


In [7]:
# Tra in YOLOv5s on COCO128 for 3 epochs
!python3 train.py --img 640 --batch 10 --epochs 20 --data SEED.yaml --weights yolov5s.pt --cache

train: weights=yolov5s.pt, cfg=, data=SEED.yaml, hyp=data/hyps/hyp.scratch-low.yaml, epochs=20, batch_size=10, imgsz=640, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, noplots=False, evolve=None, evolve_population=data/hyps, resume_evolve=None, bucket=, cache=ram, image_weights=False, device=, multi_scale=False, single_cls=False, optimizer=SGD, sync_bn=False, workers=8, project=runs/train, name=exp, exist_ok=False, quad=False, cos_lr=False, label_smoothing=0.0, patience=100, freeze=[0], save_period=-1, seed=0, local_rank=-1, entity=None, upload_dataset=False, bbox_interval=-1, artifact_alias=latest, ndjson_console=False, ndjson_file=False
github: ⚠️ YOLOv5 is out of date by 28 commits. Use 'git pull' or 'git clone https://github.com/ultralytics/yolov5' to update.
YOLOv5 🚀 v7.0-284-g95ebf68f Python-3.12.1 torch-2.3.0 CPU

hyperparameters: lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.

In [19]:
!python3 detect.py --weights /Users/jashtandel/SEM6/UAS/COMP_AGRI/yolov5/runs/train/exp12/weights/best.pt --img 640 --conf 0.20  --iou 0.03  --source /Users/jashtandel/Downloads/160524_DronesFAA_Quinn-1250x650.jpg

detect: weights=['/Users/jashtandel/SEM6/UAS/COMP_AGRI/yolov5/runs/train/exp12/weights/best.pt'], source=/Users/jashtandel/Downloads/160524_DronesFAA_Quinn-1250x650.jpg, data=data/coco128.yaml, imgsz=[640, 640], conf_thres=0.2, iou_thres=0.03, max_det=1000, device=, view_img=False, save_txt=False, save_csv=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False, vid_stride=1
YOLOv5 🚀 v7.0-284-g95ebf68f Python-3.12.1 torch-2.3.0 CPU

Fusing layers... 
Model summary: 157 layers, 7020913 parameters, 0 gradients, 15.8 GFLOPs
image 1/1 /Users/jashtandel/Downloads/160524_DronesFAA_Quinn-1250x650.jpg: 352x640 11 Alive Trees, 1 Dead Tree, 3 Debriss, 73.3ms
Speed: 0.5ms pre-process, 73.3ms inference, 0.4ms NMS per image at shape (1, 3, 640, 640)
Results saved to runs/detect/exp15


In [10]:
import torch
import yaml

# Replace with your model path and label map path
model = torch.load('runs/train/exp2/weights/best.pt')
model.eval()  # Set to evaluation mode

with open('/Users/jashtandel/SEM6/UAS/COMP_AGRI/yolov5/data/SEED.yaml', 'r') as f:
    label_map = yaml.safe_load(f)


AttributeError: 'dict' object has no attribute 'eval'

In [ ]:
import torch

model = torch.load('runs/train/exp2/weights/last.pt', map_location='cpu')  # Load on CPU
# Other options: map_location='cuda' if using GPU, None 
print(type(model))

In [ ]:
pip install supervision

In [ ]:
model_path = "/Users/jashtandel/SEM6/UAS/COMP_AGRI/yolov5/runs/train/exp2/weights/best.pt"  # Example path



In [ ]:
import torch
import yaml
from supervision import Model  # Import Model class

# ... rest of your code

model = Model(model_path, map_location="cuda")  # Or "cuda" if using GPU


In [ ]:
pip show supervision

In [ ]:
!python detect.py --weights runs/train/exp2/weights/best.pt --img 640 --conf 0.20  --iou 0.10  --source /Users/jashtandel/SEM6/6.jpg


In [ ]:
result


In [ ]:
import subprocess
import torch

# Load the YOLOv5 model directly using torch
model = torch.hub.load('ultralytics/yolov5', 'custom', path='/Users/jashtandel/SEM6/UAS/COMP_AGRI/yolov5/runs/train/exp2/weights/best.pt')

# Specify image path
image_path = '/Users/jashtandel/SEM6/6.jpg'

# Perform inference and store results
results = model(image_path)  # YOLOv5 model directly outputs results






In [ ]:
import torch
import torch.nn.functional as F

# Replace with the file path to your YOLOv5s (or other desired model) weights file
model_path = "/Users/jashtandel/SEM6/UAS/COMP_AGRI/yolov5/runs/train/exp2/weights/best.pt"

# Set the class name for seeds (replace with "your_seed_class_name" if different)
seed_class_name = "Seed"

# Set the image path (replace with your image path)
image_path = "/Users/jashtandel/SEM6/6.jpg"

# Load the YOLOv5 model
model = torch.hub.load('ultralytics/yolov5', 'custom', path=model_path)

# Perform inference on the image
results = model(image_path)

# Filter detections for the 'seed' class
seed_detections = results[results.pandas().xyxy[0]["name"] == seed_class_name]

# Count the number of seed detections
num_seeds = len(seed_detections)

# Print the results
print(f"Number of seeds detected: {num_seeds}")


In [ ]:
import torch
model_path = "/Users/jashtandel/SEM6/UAS/COMP_AGRI/yolov5/runs/train/exp2/weights/best.pt"
# Model
model = torch.hub.load('ultralytics/yolov5', 'custom', path=model_path)  # yolov5n - yolov5x6 official model
#                                            'custom', 'path/to/best.pt')  # custom model

# Images
im = '/Users/jashtandel/SEM6/6.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.
results.xyxy[0]  # im predictions (tensor)

In [ ]:
import pandas as pd

# Assuming results.xyxy[0] is a list of class names
class_names = results.xyxy[0]
num_labels = len(set(class_names))  # Count unique values

print(f"Number of output labels: {num_labels}")


In [ ]:
import torch

# Model path (replace with your actual path)
model_path = "/Users/jashtandel/SEM6/UAS/COMP_AGRI/yolov5/runs/train/exp2/weights/best.pt"

# Image path (replace with your actual path)
image_path = "/Users/jashtandel/SEM6/6.jpg"

# Class name for seeds (adapt if different)
seed_class_name = "Seed"

# Confidence threshold (adjust as needed)
confidence_threshold = 0.25

# Load the YOLOv5 model
model = torch.hub.load('ultralytics/yolov5', 'custom', path=model_path)

# Perform inference on the image
results = model(image_path)

import supervision as sv

detections = sv.Detections.from_ultralytics(results)





In [ ]:
import numpy as np
from ultralytics import YOLO

model = YOLO('/Users/jashtandel/SEM6/UAS/COMP_AGRI/yolov5/runs/train/exp/weights/best.pt')
result=model.predict(
   source='/Users/jashtandel/SEM6/Train_data/images/train/7xm.xyz889804.jpg',
   conf=0.45,
    save=True
)

In [ ]:
import numpy as np
from yolov5.models.experimental import attempt_load
from yolov5.utils.general import non_max_suppression

# Load YOLOv5 model
model = attempt_load('/Users/jashtandel/SEM6/UAS/COMP_AGRI/yolov5/runs/train/exp/weights/best.pt')

# Perform inference
result = model(['/Users/jashtandel/SEM6/Train_data/images/train/7xm.xyz889804.jpg'], conf_thres=0.45, save=True)

# Print results
print(result)


In [ ]:
import torch
from PIL import Image
from torchvision import transforms

# Load YOLOv5 model
model = torch.hub.load('ultralytics/yolov5', 'custom', path='/Users/jashtandel/SEM6/UAS/COMP_AGRI/yolov5/runs/train/exp/weights/best.pt')
model.conf = 0.25  # confidence threshold (0-1)
model.iou = 0.10
# Load image
image_path = '/Users/jashtandel/SEM6/Train_data/images/train/7xm.xyz889804.jpg'
img = Image.open(image_path)

# Define transforms
transform = transforms.Compose([
    transforms.Resize((640, 640)),
    transforms.ToTensor(),
])

# Apply transforms to image
img_tensor = transform(img).unsqueeze(0)  # Add batch dimension

# Perform inference with thresholding value
results = model(img_tensor)  # Adjust the threshold and IoU value as needed

# Print results
results.print()
results.xyxy[0]
results.pandas().xyxy[0]


In [ ]:
import numpy as np

re = results.pandas().xyxy
total = np.shape(re)[0]    # total number of images
print('total images =', total)

unf = np.array([])     # number of unfrozen droplets 
sl = np.array([])     # slices / #images 

c = 1
while c <= total:
   
   for i in re:
           
       n = np.shape(i)[0]   # number of detected objects in each slice/image 
       
       if n > 0:
           
           unf = np.append(unf,n)
           sl = np.append(sl,c)
           
       c += 1
                                      
print(unf) 
print (sl)  

In [13]:
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'custom', path='/Users/jashtandel/SEM6/UAS/COMP_AGRI/yolov5/runs/train/exp12/weights/best.pt')  # or yolov5m, yolov5l, yolov5x, etc.
# model = torch.hub.load('ultralytics/yolov5', 'custom', 'path/to/best.pt')  # custom trained model
model.conf = 0.20  # confidence threshold (0-1)
model.iou = 0.10
# Images
im = '/Users/jashtandel/SEM6/Train_data/images/train/7xm.xyz889804.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.

results.xyxy[0]  # im predictions (tensor)
results.pandas().xyxy[0]  

Using cache found in /Users/jashtandel/.cache/torch/hub/ultralytics_yolov5_master
YOLOv5 🚀 v7.0-284-g95ebf68f Python-3.12.1 torch-2.3.0 CPU

Fusing layers... 
Model summary: 157 layers, 7020913 parameters, 0 gradients, 15.8 GFLOPs
Adding AutoShape... 
image 1/1: 1000x1388 113 Alive Trees, 10 Beetle-Fire Trees, 1 Dead Tree, 2 Debriss
Speed: 57.4ms pre-process, 100.0ms inference, 2.7ms NMS per image at shape (1, 3, 480, 640)


xmin        ymin         xmax        ymax  confidence  class  \
0     546.124817   73.830254   621.377563  180.749344    0.846481      0   
1    1178.465332  523.273499  1346.400024  632.533508    0.832310      0   
2     880.592957  741.857788   966.398438  849.058167    0.818883      0   
3     586.012207  842.203735   670.183960  933.641052    0.811297      0   
4     814.644287  845.024780   903.670898  926.193909    0.810185      0   
..           ...         ...          ...         ...         ...    ...   
121  1223.993042  739.755493  1340.772827  797.610413    0.220821      0   
122   117.157547  233.142151   220.703171  315.211823    0.220671      1   
123  1001.150696  263.112366  1065.842285  317.860260    0.214497      1   
124  1092.369385  539.394043  1161.254395  593.608826    0.204150      3   
125   109.303635  365.336517   207.648911  456.438263    0.202237      1   

                 name  
0          Alive Tree  
1          Alive Tree  
2          Alive Tree  
3          Alive Tree  
4          Alive Tree  
..                ...  
121        Alive Tree  
122  Beetle-Fire Tree  
123  Beetle-Fire Tree  
124            Debris  
125  Beetle-Fire Tree  

[126 rows x 7 columns]

In [14]:
import numpy as np

re = results.pandas().xyxy
total = np.shape(re)[0]    # total number of images
print('total images =', total)

unf = np.array([])     # number of unfrozen droplets 
sl = np.array([])     # slices / #images 

c = 1
while c <= total:
   
   for i in re:
           
       n = np.shape(i)[0]   # number of detected objects in each slice/image 
       
       if n > 0:
           
           unf = np.append(unf,n)
           sl = np.append(sl,c)
           
       c += 1
                                      
print(unf) 
print (sl)  

total images = 1
[        126]
[          1]


In [22]:
import cv2 as cv
#read the image
image = cv.imread("/Users/jashtandel/SEM6/Train_data/images/train/1pNHefkfOXP_jpg.rf.0dffb180a1e683a749dccd66c26692da.jpg")
#convert the image to RGB (images are read in BGR in OpenCV)
RGB = cv.cvtColor(image, cv.COLOR_BGR2RGB)
#print the image array
print(RGB)
print("")
#print the shape of the image array
print(RGB.shape)

[[[104  94  92]
  [155 145 143]
  [162 153 148]
  ...
  [ 63  58  26]
  [ 76  71  31]
  [137 133  86]]

 [[255 245 243]
  [161 151 149]
  [135 126 121]
  ...
  [ 55  50  18]
  [ 94  89  47]
  [131 127  80]]

 [[ 94  84  82]
  [126 116 114]
  [176 167 162]
  ...
  [ 82  76  42]
  [ 92  87  45]
  [108 104  57]]

 ...

 [[132 112  87]
  [124 104  79]
  [122 102  77]
  ...
  [108  89  49]
  [109  86  52]
  [132 107  76]]

 [[130 109  82]
  [129 109  82]
  [129 109  82]
  ...
  [108  88  51]
  [118  95  64]
  [118  94  66]]

 [[116  95  66]
  [127 106  77]
  [127 107  80]
  ...
  [128 108  71]
  [125 101  73]
  [119  95  69]]]

(1024, 1024, 3)
